# This workflow sets up a Node.js environment.

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setupNodeJS:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v6.2.0
    - name: Set up Node.js environment
      uses: actions/setup-node@v6.2.0
      with:
        node-version: v6.2.0
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install yarn dependencies
      run: yarn
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
